# Generated by Django 3.2.5 on 2023-05-22 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listings_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_alter_wallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='date_cancelled',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_delivered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.TextField(default='Ordered'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('review', models.TextField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.listings')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
